/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author utkus
 */
public class ProductEditPanel extends javax.swing.JFrame {

    /**
     * Creates new form ProductEditPanel
     */
    ArrayList<Product> newList2;
    ArrayList<Product> searchList2;
    JavaProject ins = new JavaProject();
    DefaultTableModel tabModel2;
    public static int pos2 = 0;
    boolean opos2 = false;
    static String[] imageList2;
    ArrayList<Product> ImList2;
    boolean returnStats = true;
    public ProductEditPanel() {
        initComponents();
        addRowsToJtable();
    }
    
    
    public ProductEditPanel(boolean getStats){ // customer enterance
        initComponents();
        addRowsToJtable();
        this.returnStats = getStats;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        editUpdateButton = new javax.swing.JButton();
        editAddButton = new javax.swing.JButton();
        editProductName = new javax.swing.JTextField();
        editTypeName = new javax.swing.JTextField();
        editStockName = new javax.swing.JTextField();
        editPriceName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product", "Type", "Stock", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        editJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(editJTable);

        jLabel1.setText("Product");

        jLabel2.setText("Type");

        jLabel3.setText("Stock");

        jLabel4.setText("Price");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editUpdateButton.setText("Update");
        editUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUpdateButtonActionPerformed(evt);
            }
        });

        editAddButton.setText("Add New Product");
        editAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(editProductName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editStockName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editTypeName, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(editPriceName)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editAddButton)
                                .addGap(18, 18, 18)
                                .addComponent(editUpdateButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(editProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(editTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(editStockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(editPriceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editAddButton)
                            .addComponent(editUpdateButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public int getSelectedtableRow(){
       //  tabModel = (DefaultTableModel)tblMovies.getModel();
         int selectedRowIndex = editJTable.getSelectedRow();
         return selectedRowIndex;
    }
    
    public void addRowsToJtable(){
        tabModel2 = (DefaultTableModel)editJTable.getModel();
        Object rowData[] = new Object[4];
            
        newList2 = ins.loadListWithDB();
        clearetable();
        for (int i = 0; i < newList2.size(); i++) {
            tabModel2.insertRow(tabModel2.getRowCount(), new Object[]{newList2.get(i).getProductId(), newList2.get(i).getProductName(), newList2.get(i).getProductType(), newList2.get(i).getStock(), newList2.get(i).getPrice()});
        } 
    }
    
   public void clearetable(){
       tabModel2 = (DefaultTableModel)editJTable.getModel();
       int countRows = tabModel2.getRowCount();
       for (int i = countRows - 1; i >= 0; i--) {
           tabModel2.removeRow(i);
       }
   }
    
    private void editUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUpdateButtonActionPerformed
        
        ArrayList<Product> pList = ins.loadListWithDB();
        String newProduct;
        String newType;
        int newPrice;
        int newStock;
        int i = getSelectedtableRow();
        boolean bool = false;
        String temp1 = editPriceName.getText();
        String temp2 = editStockName.getText(); 
        
               try{
                   if(pList.get(i).getProductName() != editPriceName.getText()){
                    newProduct = editProductName.getText();
                   }else{
                    newProduct = pList.get(i).getProductName(); 
                   } 
                   if(pList.get(i).getPrice() != Integer.parseInt(temp1)){
                        newPrice = Integer.parseInt(temp1);          
                    }else{
                    newPrice =  pList.get(i).getPrice();
               
                   }  
                   if(pList.get(i).getStock() != Integer.parseInt(temp2)){
                    
                    newStock =  Integer.parseInt(temp2);
                    pList.get(i).setStock(newStock);
                   }else{
                        newStock =  pList.get(i).getStock();
                   }
                    if(pList.get(i).getProductType() != editTypeName.getText()){
                     newType = editTypeName.getText();
                   }else{
                      newType =  pList.get(i).getProductType(); 
                   } 
               
                 
               ins.UpdateAll(pList.get(i).getProductId(),newProduct, newType, newPrice, newStock);;  
               addRowsToJtable();  
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Please Select product ");
             } 
        
    }//GEN-LAST:event_editUpdateButtonActionPerformed

    private void editJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editJTableMouseClicked
        ArrayList<Product> newL = ins.loadListWithDB();
        int row = editJTable.getSelectedRow();
    
        editProductName.setText(editJTable.getModel().getValueAt(row, 1).toString());
        editTypeName.setText(editJTable.getModel().getValueAt(row, 2).toString());
        editStockName.setText(editJTable.getModel().getValueAt(row, 3).toString());
        editPriceName.setText(editJTable.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_editJTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        if(returnStats){
            new ShowProductPanel().setVisible(true);
        }else{
            new ShowProductPanel(returnStats).setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddButtonActionPerformed
                ArrayList<Product> pList = ins.loadListWithDB();
        int uId = editJTable.getRowCount();
        Random rand = new Random();
        int selected = rand.nextInt(1000);
        int i= 0;
        while(uId == i){
            if(!(pList.isEmpty())){
                if(pList.get(i).getProductId() == selected){
                selected = rand.nextInt(100);
                i = 0;
              }
            }
            
            i++;
        } 
     
        try{
            ins.insertNewRecordToDatabase(selected,editProductName.getText(), Integer.parseInt(editStockName.getText()), editTypeName.getText(), Integer.parseInt(editPriceName.getText()));
            addRowsToJtable(); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please, fill all required fields ");
        }
    }//GEN-LAST:event_editAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductEditPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductEditPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductEditPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductEditPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductEditPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editAddButton;
    private javax.swing.JTable editJTable;
    private javax.swing.JTextField editPriceName;
    private javax.swing.JTextField editProductName;
    private javax.swing.JTextField editStockName;
    private javax.swing.JTextField editTypeName;
    private javax.swing.JButton editUpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
